3
Guess the Number

Sample Run of Guess the Number

Source Code for Guess the Number

Importing the random Module

Generating Random Numbers with the
random.randint() Function

Welcoming the Player

Flow Control Statements

  Using Loops to Repeat Code
  Grouping with Blocks
  Looping with for Statements

Getting the Player’s Guess

Converting Values with the int(), float(), and str() Functions

The Boolean Data Type

  Comparison Operators
  Checking for True or False with Conditions
  Experimenting with Booleans, Comparison Operators, and Conditions
  The Difference Between = and ==

if Statements

Leaving Loops Early with the break Statement

Checking Whether the Player Won

Checking Whether the Player Lost

Summary

4
A Joke-Telling Program
....
.....
......
.......




